# syntax=docker/dockerfile:1

# Use node image for base image.
FROM node:21.6.0-alpine

# Set working directory.
WORKDIR /usr/src/app

# Install dependencies.
COPY package*.json ./
RUN npm install

# Copy the rest of the source files.
COPY . .

# Set environment variable for development.
ENV NODE_ENV=development

# Expose port 3000.
EXPOSE 3000

# Start the Next.js development server.
CMD ["npm", "run", "dev"]